### PR TITLE
eliminate the pointless empty guardedHandlers property

### PR DESCRIPTION
**Pull request by dherman**

### CODE REVIEW

**Comment by mikesherov** [comment]
back out the gaurdedHandlers change until we can get conformation from @ariya here.

**Comment by mikesherov** [comment]
because the rest you can land :+1:

**Comment by mikesherov** [comment]
The directive change was to simply add a "directive" property to expression statement, so I think you might just accidentally botched this PR. Closing for now.

**Comment by dherman** [comment]
Sorry I was sloppy. I've separated the guardedHandlers issue into issue #24 and I will submit a proper PR for the directive property.

**Pull request closed without merging**
