### PR TITLE
Allow only Pattern and MemberExpression in assignment target.

### PR DESCRIPTION
**Pull request by RReverser**
Redefinition of #20 with valid split of responsibilities and note for consumers.

/cc @mikesherov @dherman

### CODE REVIEW

**Comment by mikesherov** [comment]
I'll defer to @ariya and esprima team here.

**Comment by dherman** [comment]
I'm :+1: on this with just a couple of nits.

**Comment by ariya** [comment]
:+1:

**Comment by RReverser** [comment]
Thanks!

**Pull request merged**
