### PR TITLE
ImportDeclaration: no longer inherit from Declaration

### PR DESCRIPTION
**Pull request by mikesherov**
See https://github.com/estree/estree/pull/38#discussion_r25689216

This requires no code or data structure changes from Esprima, SpiderMonkey, nor Acorn. 

Thoughts? /cc @sebmck @impinball @RReverser @ariya @dherman ?

### CODE REVIEW

**Comment by caridy** [comment]
:+1:

**Comment by jeffmo** [comment]
+1

**Comment by dherman** [comment]
:+1:

**Comment by mikesherov** [comment]
Just need @sebmck or @RReverser here, and I can merge.

**Comment by RReverser** [comment]
@mikesherov I probably lost the context - could you please remind what does this give to us?

**Comment by mikesherov** [comment]
@rreverser, it allows the definition of `ExportDeclaration.declaration` to be: `Declaration|Expression|null` instead of having to specify all the different declarations that aren't import or export declarations. This also matches the specs definition of a declaration, in that it excludes import and export declarations.

**Comment by RReverser** [comment]
> it allows the definition of `ExportDeclaration.declaration` to be: `Declaration|Expression|null`

But this PR is for `ImportDeclaration`, isn't it? How does it affect `ExportDeclaration.declaration`?

**Comment by mikesherov** [comment]
Yes, this changes ImportDeclaration to not extend from `Declaration` which allows the type of `ExportDeclaration.declaration` to be `Declaration`.

If `ImportDeclaration` extends from `Declaration`, then you can't say `ExportDeclaration.declaration` allows `Declaration` because that would allow nonsense like: `export default import * from foo;`

**Comment by RReverser** [comment]
Changing parent of `ImportDeclaration` doesn't change what it can import or what can `ExportDeclaration` export, so I don't see how `export default import * from foo;` example is related to this (but I might be missing something).

This might be different in semantic spec, but in AST, `Declaration`-derived nodes are those that create local bindings (declarations) - `VariableDeclaration`, `FunctionDeclaration`, and `ImportDeclaration` perfectly matches those.

**Comment by mikesherov** [comment]
@rreverser, it's not about what Import can import. It's only about the list of allowed types in `ExportDeclaration.declaration`. 

If ImportDeclaration and ExportDeclaration are considered children of `Declaration` (which they aren't semantically nor does making them such in the AST offer any advantage considering declarations don't add any fields) then when we specify the values for `ExportDeclaration.declaration` wed have to say: `declaration: variableDeclaration|ClassDeclaration|FunctionDeclaration|Expression|null` instead of just `declaration: Declaration|Expression|null`.

**Comment by mikesherov** [comment]
Also, you can't just place an ImportDeclaration everywhere a declaration is valid. Having `ImportDeclaration` extend `Declaration` violates Liskov substitution principle, which is important to mutating consumers of the AST, like Babel.

**Comment by RReverser** [comment]
I agree that `ExportDeclaration` should not to derive from `Declaration`, as it should have real declarations in `declaration` field, but `ImportDeclaration` is different: in opposite to `ExportDeclaration` which just wraps other declarations, `ImportDeclaration` is declaration itself as it introduces ("declares") local bindings with predefined values.

**Comment by RReverser** [comment]
> Also, you can't just place an ImportDeclaration everywhere a declaration is valid. Having ImportDeclaration extend Declaration violates Liskov substitution principle, which is important to mutating consumers of the AST, like Babel.

I guess I finally got what you mean. Thanks for explanations, makes perfect sense now.

**Comment by mikesherov** [comment]
> And sorry for taking time, just needed to figure out reasoning behind)

No worries. That's why we're all here! I'm going to merge this now.

**Comment by impinball** [comment]
Sorry for that oversight on my previous PR... Thanks. ;)

**Pull request merged**
