### PR TITLE
add do-expressions

### PR DESCRIPTION
**Pull request by JLHwung**
## [View Rendered Text](https://github.com/JLHwung/estree/blob/do-expressions/experimental/do-expressions.md)

This PR adds support to [Do expressions] proposal. It reflects Babel's current approach.

[Do expressions]: https://github.com/tc39/proposal-do-expressions/

### CODE REVIEW

**Comment by RReverser** [comment]
I thought these were pretty much abandoned - do we want to document them still?

**Comment by michaelficarra** [comment]
@RReverser They're on next week's TC39 agenda, so not entirely abandoned.

**Comment by RReverser** [comment]
Ah great. Just no activity on the repo, which seems surprising if it's still developed.

**Comment by JLHwung** [comment]
@RReverser I think we should wait for approval from @nzakas.

**Comment by RReverser** [comment]
Maybe... We probably should write down somewhere on what we expect on experimental proposals after all. Personally, I don't mind them being merged with one review / without waiting for me if someone already took a look, but encoding that somewhere would be good.

**Pull request merged**
