### PR TITLE
Module specifiers inherit from Node

### LINKED ISSUE #74: Module specifiers do not inherit from Node
`ExportSpecifier`, `ImportSpecifier`, `ImportDefaultSpecifier`, and `ImportNamespaceSpecifier` do not inherit directly or indirectly from `Node`. Is this intentional? I looked through #11 and #35 but couldn't find any discussion to indicate that that would be the case.

I investigated and found that jquery/esprima#1149 will attach `loc` to all four node types when requested. The ast-types implementation does not have modules as they are currently specified, but it does have specifiers inherit from [an abstract `Specifier` type](https://github.com/benjamn/ast-types/blob/master/def/es6.js#L162), which itself inherits from `Node`.

### PR DESCRIPTION
**Pull request by btmills**
Fixes #74

### CODE REVIEW

**Comment by michaelficarra** [comment]
LGTM.

**Comment by RReverser** [comment]
Probably worth adding abstract base like:
```
interface Specifier <: Node {
  local: Identifier;
}
```
and inheriting from it?

**Comment by impinball** [comment]
Probably a good idea.

**Comment by btmills** [comment]
Updated to inherit from a new `Specifier` type.

**Comment by RReverser** [comment]
LGTM!

**Comment by btmills** [comment]
Is there any likelihood that in the future there will be other types of specifiers not related to modules? If that's a possibility, the new base could be named `ModuleSpecifier` instead.

**Comment by RReverser** [comment]
Dunno. Theoretically, yes, but this is just an abstract interface so we can safely rename it in future without breaking most tools, but you can rename it now to `ModuleSpecifier` just to be 100% sure.

**Comment by btmills** [comment]
Renamed.

**Comment by RReverser** [comment]
Cool! Any other concerns before merging this, anyone?

**Comment by nzakas** [comment]
:+1:

**Comment by RReverser** [comment]
Merging as a non-breaking.

**Pull request merged**
