### PR TITLE
Add export extensions repo

### PR DESCRIPTION
**Pull request by hzoo**
Figured it could just be a link (or we could copy it over)

### CODE REVIEW

**Comment by RReverser** [comment]
@hzoo We can also put it as a submodule in `experimental` that always points to the `master` of that repo. Github resolves submodules within Github as regular links anyway.

**Comment by hzoo** [comment]
@RReverser k, not sure if I did it correctly but I ran `git submodule add -b master git@github.com:leebyron/ecmascript-more-export-from.git`

**Comment by RReverser** [comment]
Seems to work - I can see it as folder here: https://github.com/hzoo/estree/tree/patch-3/experimental

**Comment by RReverser** [comment]
Thanks @leebyron and @hzoo!

**Pull request merged**
