### PR TITLE
Add participating members

### PR DESCRIPTION
**Pull request by mikesherov**
Thought it would be good to say who is participating in this endeavor so we can showcase the breadth of support we intend to deliver on.

@rreverser @dherman are you guys OK with being listed here as noted?

### CODE REVIEW

**Comment by RReverser** [comment]
Sure. Also, could you please add me to the org or is it for Esprima team only?

**Comment by mikesherov** [comment]
Heck, I'm not even on the org yet! I think only @dherman is!

**Comment by RReverser** [comment]
Ah ok :)

**Comment by mikesherov** [comment]
@sebmck you may also want to add yourself and the 6to5 project. Just didn't want to make assumptions.

**Comment by caridy** [comment]
:+1:

**Comment by sebmck** [comment]
@mikesherov Sure.

**Pull request closed without merging**
