### PR TITLE
add hashbang support

### PR DESCRIPTION
**Pull request by JLHwung**
## [View Rendered Text](https://github.com/JLHwung/estree/blob/hashbang/experimental/hashbang.md)

This PR adds stage-3 [Hashbang Grammar] support. It reflects on Babel's current approach.

[Hashbang Grammar]: https://github.com/tc39/proposal-hashbang

### CODE REVIEW

**Comment by RReverser** [comment]
Hmm I'm not sure about this one. Hash bang is more of a comment, really, and has no associated JavaScript semantics.

Acorn supported it under a separate option for couple of years now, and used to just ignore it as any other comment.

To me, it seems like that's what ESTree should do as well here.

**Comment by nzakas** [comment]
I think this comes down to whether or not we want to treat this as a comment. If it's a comment, then it would make sense to leave out of ESTree; if it's a directive, then it would make sense to include. I can see an argument either way.

**Comment by RReverser** [comment]
@nzakas This is probably a good generic question for #219, but in general the way I see it is that anything that doesn't have associated JavaScript semantics, doesn't matter for us.

For example, comments like `//eslint-ignore` or `//@ts-check` could be argued to be directives as well, but in the context of ECMAScript, and, correspondingly, ESTree, they don't matter since they have semantics only within their respective runtime environments.

Hashbang is very similar in this regard - it doesn't matter in context of ECMAScript / ESTree, but has semantics in its respective runtime environment (Unix).

**Comment by mysticatea** [comment]
As per the spec, shebang is a comment:

> Hashbang Comments are location-sensitive and like other types of comments are discarded from the stream of input elements for the syntactic grammar.
> ```
> HashbangComment::
>     #! SingleLineCommentCharsopt_opt
> ```
> https://tc39.es/proposal-hashbang/out.html#prod-HashbangComment

Therefore, ESTree's AST should not contain it as same as other comments.

**Comment by RReverser** [comment]
Thanks @mysticatea! @nzakas @JLHwung - do you agree given the new information above, should we close this?

**Comment by nzakas** [comment]
I'm fine with treating as a comment.

**Comment by JLHwung** [comment]
Closing this as hashbang is considered a comment and thus should not be included in estree.

**Pull request closed without merging**
