### PR TITLE
js->ts;remove hard break line; jsonc -> js+json

### PR DESCRIPTION
**Pull request by xp44mm**
\`\`\`js->\`\`\`ts;
remove hard break line; 
\`\`\`jsonc -> \`\`\`js+\`\`\`json

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks for helping. I’m not sure it makes much sense to change JS to ts considering that these blocks do not contain typescript code, but rather a custom syntax used just in ESTree.

**Comment by xp44mm** [comment]
the `interface` and `enum` is keyword in ts. This is a step in the right direction.

**Comment by nzakas** [comment]
Thanks, we will stick with what we have.

**Comment by xp44mm** [comment]
you welcome!

**Pull request closed without merging**
