### PR TITLE
Added Exponentiation Operator

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Proposal: https://github.com/rwaldron/exponentiation-operator

### CODE REVIEW

**Comment by RReverser** [comment]
Thinking whether we can use smth like `extend enum` instead. @dherman thoughts on extending DSL?

**Comment by hzoo** [comment]
Anything preventing this from being merged?

**Comment by RReverser** [comment]
@hzoo See my comment above.

**Comment by RReverser** [comment]
Nah, let's do it. @nicolo-ribaudo do you want to rename file to the top-level `es7.md` instead?

**Comment by hzoo** [comment]
Maybe just merge it manually?

**Comment by nicolo-ribaudo** [comment]
Sorry for the delay, I updated the pr.

**Comment by RReverser** [comment]
@mikesherov @nzakas @ariya I assume all good given how long this was around?

**Comment by mikesherov** [comment]
:+1:

**Pull request merged**
